name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (if needed for your build process)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies (if needed)
      run: npm install  # or yarn install, depending on your project setup

    - name: Build the project (if needed)
      run: npm run build  # or the appropriate build command for your project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Adjust this to your build output directory

